#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

print_records ()
{
record="$(dig ${2}.${1} | awk 'NR==14 { print $4 }')"

IP="$(dig ${2}.${1} | awk 'NR==14 { print $5 }')"

echo "The subdomain $2 is a $record record and points to $IP"
}


# Check number of arguments passed to script
if [ "$#" -ne 2 ];
then
    print_records $1 "www"
    print_records $1 "33763-lb-01"
    print_records $1 "33763-web-01"
    print_records $1 "33763-web-02"
else
    print_records $1 $2
fi
