#!/usr/bin/env bash
# Script displays information about subdomains of a domain

domain_records () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_records "$1" "www"
  domain_records "$1" "33763-lb-01"
  domain_records "$1" "33763-web-01"
  domain_records "$1" "33763-web-02"
elif [ "$#" == 2 ]
then
  domain_records "$1" "$2"
fi
