#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"                       
sudo apt-get update -y
sudo apt-get install nginx -y
sudo tee -i /var/www/html/index.nginx-debian.html <<< 'Hello world!'
sudo service nginx start
