#!/usr/bin/env bash
# Installs Nginx web server
#Configure to listen on port 80

apt-get -y  update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
tee /var/www/html/index.html <<< 'Hello world!'
service nginx start
