#!/usr/bin/bash
# Script that configures a new Ubuntu machine to respect above requirements

apt-get update -y
apt-get install -y nginx

#code to create a 301 permanent redirect
echo "Hello World!" | tee -i /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me http:\/\/www.html2md.software permanent;"
sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

service nginx restart
