#!/usr/bin/bash
# configures a web service on a new Ubuntu machine to respect given requirements
apt-get -y update
apt-get -y install nginx

tee -i /var/www/html/index.html <<< 'Hello world!'; string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/ugox.tech permanent;"
sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
