#!/usr/bin/bash
# Script that configures a new Ubuntu machine to respect above requirements

apt-get update -y
apt-get install -y nginx

echo "Hello World!" | tee -i /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me http:\/\/www.html2md.software permanent;"
sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" | tee -i /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

service nginx restart
