#!/usr/bin/env bash
# Sscript that installs and configures HAProxy on lb-01 server
# Configures HAProxy to send traffic to web-01 and web-02 servers
# Distributes requests using a roundrobin algorithm
# Makes sure that HAProxy can be managed via an init script

#Update system repository
sudo apt-get -y update

#Imstall haproxy
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  ugox-frontend
        bind *:80
        mode http
        default_backend ugox-backend
backend ugox-backend
        balance roundrobin
        server 33763-web-02 100.26.250.127:80 check
        server 33763-web-01 54.87.170.244:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
