#!/usr/bin/env bash
# Debug nginx, (service (init) must say that nginx is not running before proceeding to the fix.)
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
